version: '3'

services:
  docker-jupyter-lab:
    container_name: graphQL_API
    build:
      context: .
      dockerfile: Dockerfile
    command: node server.js
    tty: true
    working_dir: '/usr/src/app/'
    volumes:
      - ./app:/usr/src/app/
    ports:
      - '8080:8080'